security:
    # Activation du gestionnaire d'authentificateurs
    enable_authenticator_manager: true

    # Encoders pour les mots de passe
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
            algorithm: auto

    # Fournisseurs d'utilisateurs
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
        # used to reload user from session & other features (e.g. switch_user)

    # Firewalls
    firewalls:
        # Désactive la sécurité pour l'environnement de développement
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Configuration principale
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator:
                - App\Security\AppCustomAuthenticator
            logout:
                path: app_logout
                target: app_login  # Redirection après déconnexion
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 2592000 # 30 jours
                path: /
                always_remember_me: true
            # Configurer les options supplémentaires si nécessaire
            # csrf_protection: true

    # Contrôle d'accès 
    
    access_control:
        - { path: ^/index, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/shop, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/contact, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/cart, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/order/new, roles: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }  # Allow public access to /register
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/dashboard, roles: ROLE_ADMIN }
        - { path: ^/, roles: ROLE_USER }
